<?php
$routes = [
    '/' => 'HomeController@index',
    '/usuario/{id}' => 'UsuarioController@show',
    '/usuarios' => 'UsuarioController@usuarios',
    '/login' => 'LoginController@index',
    '/logar' => 'LoginController@logar',
    '/alterarSenhaInicial' => 'UsuarioController@alterarSenhaInicial',
    '/logout' => 'LoginController@logout',
    '/clientes' => 'ClienteController@index',
    '/cliente/{id}' => 'ClienteController@buscaCliente',
    '/addcliente' => 'ClienteController@adicionarClienteFormulario',
    '/insertCliente' => 'ClienteController@adicionarCliente',
    '/updateCliente' => 'ClienteController@atualizarCliente',
    '/deleteCliente/{id}' => 'ClienteController@deletarCliente',
    '/produtos' => 'ProdutoController@index',
    '/produto/{id}' => 'ProdutoController@buscaProduto',
    '/getProdutos/{id}' => 'ProdutoController@getProdutos',
    '/addproduto' => 'ProdutoController@adicionarProdutoFormulario',
    '/insertProduto' => 'ProdutoController@adicionarProduto',
    '/updateProduto' => 'ProdutoController@atualizarProduto',
    '/deleteProduto/{id}' => 'ProdutoController@deletarProduto',
    '/importProdutos' => 'ProdutoController@importarCSV',
    '/configuracao' => 'ConfiguracaoController@index',
    '/solicitarComissao' => 'ConfiguracaoController@solicitarComissao',
    '/recusarNegociacao' => 'ConfiguracaoController@recusarNegociacao',
    '/aceitarComissao' => 'ConfiguracaoController@aceitarComissao',
    '/negociarComissao' => 'ConfiguracaoController@negociarComissao',
    '/buscaNegociacao/{id}' => 'ConfiguracaoController@buscaNegociacao',
    '/atualizaComissao' => 'ConfiguracaoController@atualizaComissao',
    '/attParam' => 'ConfiguracaoController@atualizarParametro',

    '/promocoes' => 'PromocaoController@index',
    '/gerenciarPromocao/{id}' => 'PromocaoController@gerenciarPromocoes',
    '/gerenciarPromocao' => 'PromocaoController@gerenciarPromocoes',

];